import { FileSearch2, ShieldAlert, ShieldCheck } from "lucide-react";

import type { EvidencePacket, VisionFinding } from "@/types";
import { Badge } from "@/components/ui/badge";
import { SUPPORT_META, titleCase } from "./agent-meta";
import { cn } from "@/lib/utils";

interface Props {
  evidence: EvidencePacket | null;
  vision: VisionFinding[];
}

/**
 * The auditable core of the system: every fact shown here was computed in Python
 * from raw telemetry — never generated by a model — and is tagged with which
 * party it supports.
 */
export function EvidencePanel({ evidence, vision }: Props) {
  if (!evidence) {
    return (
      <EmptyState icon={<FileSearch2 className="h-5 w-5" />} text="No evidence extracted yet." />
    );
  }

  const ordered = [...evidence.facts].sort((a, b) => {
    const rank = { rider: 0, driver: 1, neutral: 2 };
    return rank[a.supports] - rank[b.supports];
  });

  return (
    <div className="space-y-5">
      <p className="rounded-md border border-border bg-muted/40 px-3 py-2 text-xs leading-relaxed text-muted-foreground">
        {evidence.summary}
      </p>

      <section>
        <SectionTitle>Verified Facts</SectionTitle>
        <ul className="mt-2 space-y-1.5">
          {ordered.map((fact) => (
            <li
              key={fact.key}
              className="rounded-md border border-border bg-card/50 px-3 py-2"
            >
              <div className="flex items-start justify-between gap-3">
                <div className="min-w-0">
                  <p className="text-sm font-medium leading-snug">{fact.label}</p>
                  {fact.note && (
                    <p className="mt-0.5 text-xs leading-relaxed text-muted-foreground">
                      {fact.note}
                    </p>
                  )}
                </div>
                <div className="flex shrink-0 flex-col items-end gap-1">
                  <span className="font-mono text-sm font-semibold text-foreground">
                    {String(fact.value)}
                    {fact.unit ? <span className="ml-0.5 text-xs text-muted-foreground">{fact.unit}</span> : null}
                  </span>
                  <Badge
                    variant="outline"
                    className={cn("h-4 px-1 text-[10px]", SUPPORT_META[fact.supports].className)}
                  >
                    {SUPPORT_META[fact.supports].label}
                  </Badge>
                </div>
              </div>
              <p className="mt-1 font-mono text-[10px] uppercase tracking-wide text-muted-foreground/70">
                {fact.source}
              </p>
            </li>
          ))}
        </ul>
      </section>

      {evidence.policy_checks.length > 0 && (
        <section>
          <SectionTitle>Policy Compliance</SectionTitle>
          <ul className="mt-2 space-y-1.5">
            {evidence.policy_checks.map((check) => (
              <li
                key={check.ref}
                className={cn(
                  "flex items-start gap-2 rounded-md border px-3 py-2",
                  check.compliant
                    ? "border-emerald-500/25 bg-emerald-500/5"
                    : "border-red-500/25 bg-red-500/5",
                )}
              >
                {check.compliant ? (
                  <ShieldCheck className="mt-0.5 h-4 w-4 shrink-0 text-emerald-400" />
                ) : (
                  <ShieldAlert className="mt-0.5 h-4 w-4 shrink-0 text-red-400" />
                )}
                <div className="min-w-0">
                  <p className="text-sm leading-snug">
                    <span className="font-mono text-[11px] text-muted-foreground">
                      [{check.ref}]
                    </span>{" "}
                    {check.description}
                  </p>
                  <p className="mt-0.5 text-xs text-muted-foreground">
                    expected {check.expected} · observed {check.actual}
                  </p>
                </div>
              </li>
            ))}
          </ul>
        </section>
      )}

      {evidence.risk_signals.length > 0 && (
        <section>
          <SectionTitle>Behavioural Risk Signals</SectionTitle>
          <ul className="mt-2 space-y-1.5">
            {evidence.risk_signals.map((signal, i) => (
              <li
                key={`${signal.party}-${i}`}
                className="rounded-md border border-border bg-card/50 px-3 py-2"
              >
                <div className="flex items-center gap-2">
                  <Badge
                    variant="outline"
                    className={cn(
                      "h-4 px-1 text-[10px]",
                      signal.party === "rider"
                        ? "border-blue-500/30 bg-blue-500/15 text-blue-300"
                        : "border-amber-500/30 bg-amber-500/15 text-amber-300",
                    )}
                  >
                    {signal.party}
                  </Badge>
                  <span className="text-sm font-medium">{signal.signal}</span>
                  <Badge
                    variant="outline"
                    className={cn(
                      "ml-auto h-4 px-1 text-[10px]",
                      signal.severity === "high"
                        ? "border-red-500/30 bg-red-500/15 text-red-300"
                        : signal.severity === "medium"
                          ? "border-orange-500/30 bg-orange-500/15 text-orange-300"
                          : "border-zinc-500/30 bg-zinc-500/15 text-zinc-300",
                    )}
                  >
                    {signal.severity}
                  </Badge>
                </div>
                <p className="mt-1 text-xs text-muted-foreground">{signal.detail}</p>
              </li>
            ))}
          </ul>
        </section>
      )}

      {vision.length > 0 && (
        <section>
          <SectionTitle>Image Analysis Findings</SectionTitle>
          <ul className="mt-2 space-y-2">
            {vision.map((finding) => (
              <li
                key={finding.attachment_id}
                className={cn(
                  "rounded-md border px-3 py-2",
                  finding.genuine
                    ? "border-emerald-500/25 bg-emerald-500/5"
                    : "border-red-500/25 bg-red-500/5",
                )}
              >
                <div className="flex flex-wrap items-center gap-2">
                  <Badge
                    variant="outline"
                    className={cn(
                      "h-4 px-1 text-[10px]",
                      finding.genuine
                        ? "border-emerald-500/30 bg-emerald-500/15 text-emerald-300"
                        : "border-red-500/30 bg-red-500/15 text-red-300",
                    )}
                  >
                    {finding.genuine ? "ADMISSIBLE" : "NOT ADMISSIBLE"}
                  </Badge>
                  <span className="text-sm font-medium">
                    severity: {titleCase(finding.severity)}
                  </span>
                  {finding.ai_generated_probability !== null && (
                    <span className="font-mono text-xs text-muted-foreground">
                      AI-prob {finding.ai_generated_probability.toFixed(2)}
                    </span>
                  )}
                  {finding.exif_timestamp_delta_min !== null && (
                    <span className="font-mono text-xs text-muted-foreground">
                      EXIF Δ {finding.exif_timestamp_delta_min} min
                    </span>
                  )}
                </div>
                {finding.anomalies.length > 0 && (
                  <ul className="mt-1.5 space-y-0.5">
                    {finding.anomalies.map((a, i) => (
                      <li key={i} className="text-xs text-red-300/90">
                        • {a}
                      </li>
                    ))}
                  </ul>
                )}
                <p className="mt-1.5 text-xs leading-relaxed text-muted-foreground">
                  {finding.reasoning}
                </p>
              </li>
            ))}
          </ul>
        </section>
      )}
    </div>
  );
}

function SectionTitle({ children }: { children: React.ReactNode }) {
  return (
    <h3 className="text-[11px] font-semibold uppercase tracking-wider text-muted-foreground">
      {children}
    </h3>
  );
}

function EmptyState({ icon, text }: { icon: React.ReactNode; text: string }) {
  return (
    <div className="flex flex-col items-center justify-center gap-2 py-16 text-muted-foreground">
      {icon}
      <p className="text-sm">{text}</p>
    </div>
  );
}
