import { useRef, useState } from "react";
import {
  AudioLines,
  FileSearch2,
  Film,
  ImageIcon,
  ShieldAlert,
  ShieldCheck,
  Upload,
} from "lucide-react";

import type {
  AudioTranscript,
  EvidencePacket,
  MediaUploadResult,
  VideoAnalysis,
  VideoFrame,
  VisionFinding,
} from "@/types";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
  MEDIA_KIND_META,
  SEVERITY_META,
  SUPPORT_META,
  titleCase,
} from "./agent-meta";
import { cn } from "@/lib/utils";
import { uploadMedia } from "@/lib/api";

interface Props {
  evidence: EvidencePacket | null;
  vision: VisionFinding[];
  /** Selected case — enables the "attach your own payload" controls. */
  caseId?: string | null;
  disabled?: boolean;
  /** Miora-generated evidence assets bundled with the case. */
  assets?: string[];
}

/**
 * The auditable core of the system: every fact shown here was computed in Python
 * from raw telemetry — never generated by a model — and is tagged with which
 * party it supports.
 *
 * Phase 3 adds the multi-modal layer: TRTC transcripts with per-turn hostility
 * scoring, and video clips decomposed into 1 fps keyframes that can be scrubbed
 * frame by frame next to the ruling that cites them.
 */
export function EvidencePanel({ evidence, vision, caseId, disabled, assets }: Props) {
  if (!evidence && vision.length === 0 && !assets?.length) {
    return (
      <EmptyState icon={<FileSearch2 className="h-5 w-5" />} text="No evidence extracted yet." />
    );
  }

  const ordered = [...(evidence?.facts ?? [])].sort((a, b) => {
    const rank = { rider: 0, driver: 1, neutral: 2 };
    return rank[a.supports] - rank[b.supports];
  });

  return (
    <div className="space-y-5">
      {evidence?.summary && (
        <p className="rounded-md border border-border bg-muted/40 px-3 py-2 text-xs leading-relaxed text-muted-foreground">
          {evidence.summary}
        </p>
      )}

      {(assets?.length || vision.length > 0) && (
        <section>
          <SectionTitle>Submitted Media</SectionTitle>
          <div className="mt-2 space-y-3">
            {assets && assets.length > 0 && <AssetGallery assets={assets} />}
            {vision.map((finding) => (
              <MediaCard key={finding.attachment_id} finding={finding} poster={assets?.[0]} />
            ))}
            <MediaUploader caseId={caseId ?? null} disabled={disabled ?? false} />
          </div>
        </section>
      )}

      {ordered.length > 0 && (
        <section>
          <SectionTitle>Verified Facts</SectionTitle>
          <ul className="mt-2 space-y-1.5">
            {ordered.map((fact) => (
              <li key={fact.key} className="rounded-md border border-border bg-card/50 px-3 py-2">
                <div className="flex items-start justify-between gap-3">
                  <div className="min-w-0">
                    <p className="text-sm font-medium leading-snug">{fact.label}</p>
                    {fact.note && (
                      <p className="mt-0.5 text-xs leading-relaxed text-muted-foreground">
                        {fact.note}
                      </p>
                    )}
                  </div>
                  <div className="flex shrink-0 flex-col items-end gap-1">
                    <span className="font-mono text-sm font-semibold text-foreground">
                      {String(fact.value)}
                      {fact.unit ? (
                        <span className="ml-0.5 text-xs text-muted-foreground">{fact.unit}</span>
                      ) : null}
                    </span>
                    <Badge
                      variant="outline"
                      className={cn("h-4 px-1 text-[10px]", SUPPORT_META[fact.supports].className)}
                    >
                      {SUPPORT_META[fact.supports].label}
                    </Badge>
                  </div>
                </div>
                <p className="mt-1 font-mono text-[10px] uppercase tracking-wide text-muted-foreground/70">
                  {fact.source}
                </p>
              </li>
            ))}
          </ul>
        </section>
      )}

      {evidence && evidence.policy_checks.length > 0 && (
        <section>
          <SectionTitle>Policy Compliance</SectionTitle>
          <ul className="mt-2 space-y-1.5">
            {evidence.policy_checks.map((check, index) => (
              <li
                key={`${check.ref}-${index}`}
                className={cn(
                  "flex items-start gap-2 rounded-md border px-3 py-2",
                  check.compliant
                    ? "border-emerald-500/25 bg-emerald-500/5"
                    : "border-red-500/25 bg-red-500/5",
                )}
              >
                {check.compliant ? (
                  <ShieldCheck className="mt-0.5 h-4 w-4 shrink-0 text-emerald-400" />
                ) : (
                  <ShieldAlert className="mt-0.5 h-4 w-4 shrink-0 text-red-400" />
                )}
                <div className="min-w-0">
                  <p className="text-sm leading-snug">
                    <span className="font-mono text-[11px] text-muted-foreground">
                      [{check.ref}]
                    </span>{" "}
                    {check.description}
                  </p>
                  <p className="mt-0.5 text-xs text-muted-foreground">
                    expected {check.expected} · observed {check.actual}
                  </p>
                </div>
              </li>
            ))}
          </ul>
        </section>
      )}

      {evidence && evidence.risk_signals.length > 0 && (
        <section>
          <SectionTitle>Behavioural Risk Signals</SectionTitle>
          <ul className="mt-2 space-y-1.5">
            {evidence.risk_signals.map((signal, i) => (
              <li
                key={`${signal.party}-${i}`}
                className="rounded-md border border-border bg-card/50 px-3 py-2"
              >
                <div className="flex items-center gap-2">
                  <Badge
                    variant="outline"
                    className={cn(
                      "h-4 px-1 text-[10px]",
                      signal.party === "rider"
                        ? "border-blue-500/30 bg-blue-500/15 text-blue-300"
                        : "border-amber-500/30 bg-amber-500/15 text-amber-300",
                    )}
                  >
                    {signal.party}
                  </Badge>
                  <span className="text-sm font-medium">{signal.signal}</span>
                  <Badge
                    variant="outline"
                    className={cn(
                      "ml-auto h-4 px-1 text-[10px]",
                      signal.severity === "high"
                        ? "border-red-500/30 bg-red-500/15 text-red-300"
                        : signal.severity === "medium"
                          ? "border-orange-500/30 bg-orange-500/15 text-orange-300"
                          : "border-zinc-500/30 bg-zinc-500/15 text-zinc-300",
                    )}
                  >
                    {signal.severity}
                  </Badge>
                </div>
                <p className="mt-1 text-xs text-muted-foreground">{signal.detail}</p>
              </li>
            ))}
          </ul>
        </section>
      )}

      {vision.length > 0 && (
        <section>
          <SectionTitle>Vision Agent Findings</SectionTitle>
          <ul className="mt-2 space-y-2">
            {vision.map((finding) => (
              <li
                key={finding.attachment_id}
                className={cn(
                  "rounded-md border px-3 py-2",
                  finding.genuine
                    ? "border-emerald-500/25 bg-emerald-500/5"
                    : "border-red-500/25 bg-red-500/5",
                )}
              >
                <div className="flex flex-wrap items-center gap-2">
                  <Badge
                    variant="outline"
                    className={cn(
                      "h-4 px-1 text-[10px]",
                      finding.genuine
                        ? "border-emerald-500/30 bg-emerald-500/15 text-emerald-300"
                        : "border-red-500/30 bg-red-500/15 text-red-300",
                    )}
                  >
                    {finding.genuine ? "ADMISSIBLE" : "NOT ADMISSIBLE"}
                  </Badge>
                  <span className="text-sm font-medium">
                    severity: {titleCase(finding.severity)}
                  </span>
                  {finding.ai_generated_probability !== null &&
                    finding.ai_generated_probability !== undefined && (
                      <span className="font-mono text-xs text-muted-foreground">
                        AI-prob {finding.ai_generated_probability.toFixed(2)}
                      </span>
                    )}
                  {finding.exif_timestamp_delta_min !== null &&
                    finding.exif_timestamp_delta_min !== undefined && (
                      <span className="font-mono text-xs text-muted-foreground">
                        EXIF Δ {finding.exif_timestamp_delta_min} min
                      </span>
                    )}
                </div>
                {finding.anomalies.length > 0 && (
                  <ul className="mt-1.5 space-y-0.5">
                    {finding.anomalies.map((a, i) => (
                      <li key={i} className="text-xs text-red-300/90">
                        • {a}
                      </li>
                    ))}
                  </ul>
                )}
                <p className="mt-1.5 text-xs leading-relaxed text-muted-foreground">
                  {finding.reasoning}
                </p>
              </li>
            ))}
          </ul>
        </section>
      )}
    </div>
  );
}

// ---------------------------------------------------------------------------
// Phase 3: multi-modal media rendering
// ---------------------------------------------------------------------------

/** Backend media is mounted at `/media` on :3000 and proxied as `/api/media`. */
function mediaUrl(path: string | null | undefined): string | undefined {
  if (!path) return undefined;
  if (path.startsWith("/api/") || path.startsWith("http")) return path;
  if (path.startsWith("/media/")) return `/api${path}`;
  return path;
}

function AssetGallery({ assets }: { assets: string[] }) {
  return (
    <div className="grid grid-cols-2 gap-2">
      {assets.map((src) => (
        <figure key={src} className="overflow-hidden rounded-md border border-border bg-card/40">
          <img
            src={src}
            alt="Submitted evidence"
            loading="lazy"
            className="h-28 w-full object-cover"
            onError={(e) => {
              e.currentTarget.style.display = "none";
            }}
          />
          <figcaption className="truncate px-2 py-1 font-mono text-[10px] text-muted-foreground">
            {src.split("/").pop()}
          </figcaption>
        </figure>
      ))}
    </div>
  );
}

/** One evidence payload: image / video (with keyframes) / audio (with ASR). */
function MediaCard({ finding, poster }: { finding: VisionFinding; poster?: string }) {
  const kind = finding.media_kind ?? "image";
  const meta = MEDIA_KIND_META[kind] ?? MEDIA_KIND_META.image;
  const Icon = kind === "video" ? Film : kind === "audio" ? AudioLines : ImageIcon;

  return (
    <div
      className={cn(
        "rounded-md border px-3 py-2.5",
        finding.genuine ? "border-border bg-card/40" : "border-red-500/25 bg-red-500/5",
      )}
    >
      <div className="flex flex-wrap items-center gap-2">
        <Icon className="h-4 w-4 shrink-0 text-muted-foreground" />
        <Badge variant="outline" className={cn("h-4 px-1 text-[10px]", meta.className)}>
          {meta.label}
        </Badge>
        <span className="font-mono text-[11px] text-muted-foreground">
          {finding.attachment_id}
        </span>
        <Badge
          variant="outline"
          className={cn(
            "ml-auto h-4 px-1 text-[10px]",
            (SEVERITY_META[finding.severity] ?? SEVERITY_META.none).className,
          )}
        >
          {finding.genuine ? "ADMISSIBLE" : "REJECTED"}
        </Badge>
      </div>

      {kind === "video" && finding.video && (
        <VideoBlock analysis={finding.video} poster={poster} />
      )}
      {kind === "audio" && finding.transcript && (
        <AudioBlock transcript={finding.transcript} />
      )}
      {kind === "image" && poster && (
        <img
          src={poster}
          alt="Submitted evidence"
          loading="lazy"
          className="mt-2 max-h-40 w-full rounded border border-border object-cover"
          onError={(e) => {
            e.currentTarget.style.display = "none";
          }}
        />
      )}
    </div>
  );
}

function VideoBlock({ analysis, poster }: { analysis: VideoAnalysis; poster?: string }) {
  const src = mediaUrl(analysis.source_url);
  const [active, setActive] = useState<VideoFrame | null>(null);

  return (
    <div className="mt-2 space-y-2">
      {src && (
        <video
          key={src}
          controls
          preload="metadata"
          poster={poster}
          className="w-full rounded border border-border bg-black"
          style={{ maxHeight: "13rem" }}
        >
          <source src={src} />
          Your browser cannot play this clip.
        </video>
      )}
      <div className="flex flex-wrap items-center gap-x-3 gap-y-1 font-mono text-[10px] text-muted-foreground">
        <span>{analysis.duration_s.toFixed(1)}s</span>
        {analysis.fps !== null && <span>{analysis.fps} fps source</span>}
        {analysis.width && analysis.height && (
          <span>
            {analysis.width}×{analysis.height}
          </span>
        )}
        <span>{analysis.frames_extracted} keyframes @ 1 fps</span>
        <span>backend: {analysis.engine}</span>
        <Badge
          variant="outline"
          className={cn(
            "h-4 px-1 text-[10px]",
            (SEVERITY_META[analysis.severity] ?? SEVERITY_META.none).className,
          )}
        >
          {titleCase(analysis.severity)}
        </Badge>
      </div>

      {analysis.frames.length > 0 && (
        <div>
          <p className="mb-1 text-[10px] uppercase tracking-wide text-muted-foreground">
            Extracted keyframes — click to inspect
          </p>
          <div className="grid grid-cols-4 gap-1.5">
            {analysis.frames.map((frame) => (
              <button
                key={frame.index}
                type="button"
                onClick={() => setActive(frame === active ? null : frame)}
                title={`t=${frame.timestamp_s}s`}
                className={cn(
                  "group relative overflow-hidden rounded border transition-colors",
                  active === frame
                    ? "border-primary"
                    : "border-border hover:border-primary/50",
                )}
              >
                <img
                  src={mediaUrl(frame.path)}
                  alt={`keyframe ${frame.index}`}
                  loading="lazy"
                  className="h-14 w-full object-cover"
                  onError={(e) => {
                    e.currentTarget.style.display = "none";
                  }}
                />
                <span className="absolute bottom-0 right-0 bg-black/70 px-1 font-mono text-[9px] text-white">
                  {frame.timestamp_s}s
                </span>
              </button>
            ))}
          </div>
          {active && (
            <div className="mt-2 rounded border border-border bg-muted/40 px-2 py-1.5">
              <img
                src={mediaUrl(active.path)}
                alt={`keyframe ${active.index} enlarged`}
                className="max-h-40 w-full rounded object-contain"
                onError={(e) => {
                  e.currentTarget.style.display = "none";
                }}
              />
              <p className="mt-1 font-mono text-[10px] text-muted-foreground">
                t={active.timestamp_s}s
                {active.mean_luminance !== null && active.mean_luminance !== undefined && (
                  <> · luminance {active.mean_luminance.toFixed(2)}</>
                )}
                {active.motion_score !== null && active.motion_score !== undefined && (
                  <> · motion Δ {active.motion_score.toFixed(3)}</>
                )}
                {active.label && <> · {active.label}</>}
              </p>
            </div>
          )}
        </div>
      )}

      {analysis.anomalies.length > 0 && (
        <ul className="space-y-0.5">
          {analysis.anomalies.map((a, i) => (
            <li key={i} className="text-xs text-orange-300/90">
              • {a}
            </li>
          ))}
        </ul>
      )}
    </div>
  );
}

function AudioBlock({ transcript }: { transcript: AudioTranscript }) {
  const src = mediaUrl(transcript.source_url);
  const hostilityPct = Math.round(transcript.hostility_score * 100);

  return (
    <div className="mt-2 space-y-2">
      {src && (
        <audio key={src} controls preload="metadata" className="w-full">
          <source src={src} />
          Your browser cannot play this recording.
        </audio>
      )}

      <div className="flex flex-wrap items-center gap-2 font-mono text-[10px] text-muted-foreground">
        <span>engine: {transcript.engine}</span>
        <span>{transcript.duration_s.toFixed(0)}s</span>
        <span>{transcript.segments.length} turn(s)</span>
        <Badge
          variant="outline"
          className={cn(
            "h-4 px-1 text-[10px]",
            transcript.threat_detected
              ? "border-red-500/40 bg-red-500/15 text-red-300"
              : transcript.hostility_score >= 0.45
                ? "border-orange-500/40 bg-orange-500/15 text-orange-300"
                : "border-zinc-500/40 bg-zinc-500/15 text-zinc-300",
          )}
        >
          hostility {hostilityPct}%
          {transcript.threat_detected ? " · THREAT" : ""}
        </Badge>
      </div>

      {transcript.keywords.length > 0 && (
        <div className="flex flex-wrap gap-1">
          {transcript.keywords.map((kw) => (
            <span
              key={kw}
              className="rounded bg-red-500/10 px-1.5 py-0.5 font-mono text-[10px] text-red-300"
            >
              {kw}
            </span>
          ))}
        </div>
      )}

      <ol className="space-y-1">
        {transcript.segments.map((seg, i) => (
          <li
            key={i}
            className={cn(
              "rounded border-l-2 px-2 py-1",
              seg.hostility >= 0.45 ? "border-l-red-500 bg-red-500/5" : "border-l-border",
            )}
          >
            <div className="flex items-center gap-2">
              <span
                className={cn(
                  "rounded px-1 font-mono text-[9px] uppercase",
                  seg.speaker === "driver"
                    ? "bg-amber-500/15 text-amber-300"
                    : seg.speaker === "rider"
                      ? "bg-blue-500/15 text-blue-300"
                      : "bg-zinc-500/15 text-zinc-300",
                )}
              >
                {seg.speaker}
              </span>
              <span className="font-mono text-[9px] text-muted-foreground">
                {seg.start_s.toFixed(1)}–{seg.end_s.toFixed(1)}s
              </span>
              {seg.hostility >= 0.45 && (
                <span className="ml-auto font-mono text-[9px] text-red-300">
                  hostility {seg.hostility.toFixed(2)}
                </span>
              )}
            </div>
            <p className="mt-0.5 text-xs leading-snug text-foreground/90">{seg.text}</p>
          </li>
        ))}
      </ol>

      <p className="text-xs leading-relaxed text-muted-foreground">{transcript.summary}</p>
    </div>
  );
}

/** Attach your own audio/video payload — exercises `/upload-audio` and `/upload-video`. */
function MediaUploader({ caseId, disabled }: { caseId: string | null; disabled: boolean }) {
  const audioRef = useRef<HTMLInputElement>(null);
  const videoRef = useRef<HTMLInputElement>(null);
  const [busy, setBusy] = useState(false);
  const [note, setNote] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  const send = async (kind: "audio" | "video", file: File) => {
    if (!caseId) return;
    setBusy(true);
    setError(null);
    setNote(null);
    try {
      const result: MediaUploadResult = await uploadMedia(kind, caseId, file);
      const detail =
        kind === "audio"
          ? `${result.transcript?.segments.length ?? 0} turn(s) transcribed`
          : `${result.video?.frames_extracted ?? 0} keyframe(s) extracted`;
      setNote(`${result.attachment_id} attached — ${detail}. Run arbitration to use it.`);
    } catch (err) {
      setError(String(err));
    } finally {
      setBusy(false);
    }
  };

  if (!caseId) return null;

  return (
    <div className="rounded-md border border-dashed border-border px-3 py-2.5">
      <p className="text-[11px] font-medium">Attach a payload to this case</p>
      <p className="mt-0.5 text-[10px] leading-relaxed text-muted-foreground">
        Uploaded through <span className="font-mono">/upload-audio</span> /{" "}
        <span className="font-mono">/upload-video</span>. The ASR and keyframe
        pipelines run on it, then it is folded into the dossier on the next run.
      </p>
      <div className="mt-2 flex flex-wrap gap-2">
        <Button
          size="sm"
          variant="outline"
          className="h-7 text-xs"
          disabled={disabled || busy}
          onClick={() => audioRef.current?.click()}
        >
          <Upload className="mr-1 h-3 w-3" />
          {busy ? "Uploading…" : "Audio"}
        </Button>
        <Button
          size="sm"
          variant="outline"
          className="h-7 text-xs"
          disabled={disabled || busy}
          onClick={() => videoRef.current?.click()}
        >
          <Upload className="mr-1 h-3 w-3" />
          {busy ? "Uploading…" : "Video"}
        </Button>
        <input
          ref={audioRef}
          type="file"
          accept="audio/*"
          className="hidden"
          onChange={(e) => {
            const f = e.target.files?.[0];
            if (f) void send("audio", f);
            e.target.value = "";
          }}
        />
        <input
          ref={videoRef}
          type="file"
          accept="video/*"
          className="hidden"
          onChange={(e) => {
            const f = e.target.files?.[0];
            if (f) void send("video", f);
            e.target.value = "";
          }}
        />
      </div>
      {note && <p className="mt-2 text-[11px] text-emerald-400">{note}</p>}
      {error && <p className="mt-2 text-[11px] text-red-400">{error}</p>}
    </div>
  );
}

function SectionTitle({ children }: { children: React.ReactNode }) {
  return (
    <h3 className="text-[11px] font-semibold uppercase tracking-wider text-muted-foreground">
      {children}
    </h3>
  );
}

function EmptyState({ icon, text }: { icon: React.ReactNode; text: string }) {
  return (
    <div className="flex flex-col items-center justify-center gap-2 py-16 text-muted-foreground">
      {icon}
      <p className="text-sm">{text}</p>
    </div>
  );
}
